### ISSUE TITLE
Edit and delete seem to exhibit an extra / in the outputted uri.

### ISSUE THREAD

**Issue by jimwildman** [palmerr23/ESP32-OTA-and-File-Manager#1]
the edit and delete fails, edit seems to do nothing but if you check the uri it placed in your browser it has an extra/ ex; //filename
Same happens with the delete. I was able to solve this by commenting out lins 309 and 314 of filecode.h.
They look like so; output += path; I am not sure if there is some other need for the lines, but for my simple purpose they work.

**Comment by palmerr23** [comment]
Thanks Jim,

I'm glad you find the utility useful.

I retested the code and can't duplicate the issue with simple edit/delete tests. (SPIFFS FS, Windows host, Chrome browser).

What platform are you running on - Windows, Mac or Linux; and the browser?  These may determine what is provided as the filename to the upload function and be saved as the filename.

Are you working with SPIFFS or LittleFS on the ESP32?

Can you also check what's happening in the Serial Monitor window (can you uncomment the two lines first) - the filenames for edit and delete are output there as diagnostics. A cut and paste of the relevant lines might be helpful in working out what's happening in your setup.

**Comment by jimwildman** [comment]
The file name depicted by fname was showing in the monitor as //wifi.txt after the change it shows as /wifi.txt, using  safari on macos catalina, heltec wifi kit.

I could test it with chrome to see if the browser is the cause.

Uploading code with the ota is faster then the serial cable:)

**Comment by palmerr23** [comment]
What I'll do is insert a test for two leading / characters and remove one if there are two.

Sounds like we've simply got the OS or Browser acting differently - as both filename and path are legitimate strings.

Please test it with Chrome - as I'd be interested to see if it's browser or OS related.

Thanks.

**Comment by jimwildman** [comment]
Seems to be the same with chrome, both on my mac and from my andriod phone. 

Thanks again.

**Comment by palmerr23** [comment]
Thanks,

Sounds like the fix I described above is the one to go with.

**Comment by palmerr23** [comment]
I've added some conditional code to hopefully fix the issue.
It should no longer add the path if the leading character in the filename is '\' or '/'
Can you check if this works properly on your Mac.
Thanks
