### ISSUE TITLE
not format FS

### ISSUE THREAD

**Issue by Curioplus** [palmerr23/ESP32-OTA-and-File-Manager#3]
I try format with littlefs mode but return error.

I use the ESP32S3 1N16R8

Any aidea?

15:50:51.095 -> Mode format
15:50:51.095 -> handleMain: path [/]
15:50:51.095 -> fname:[], 0
15:50:51.095 -> text [], 0
15:50:51.095 -> mode [format], 1
15:50:51.095 -> Directory [/]not foundE (33180) SPIFFS: spiffs partition could not be found
15:50:51.095 -> No file system found. Please format it.
15:50:51.095 -> Formatting FS.
15:50:51.095 -> E (33192) SPIFFS: spiffs partition could not be found
15:50:51.095 -> Format failed.
15:50:51.095 -> main: Done formatting

**Comment by palmerr23** [comment]
Thanks for the transcript - you have a chip with FLASH, so it looks like the partition scheme selected may have been one without a SPIFFS file system.

Did you use one of the Arduino board options with SPIFFS enabled? The first and fourth from the bottom are the ones I've tested most extensively.
![Screenshot 2023-02-14 085739](https://user-images.githubusercontent.com/14856369/218583868-e1941512-5ab8-4582-a3f2-a00f1a5d3e07.png)

You can format the FS with either SPIFFS or LittleFS with either of these options.
