### ISSUE TITLE
Please specify referenced libraries in the readme

### ISSUE THREAD

**Issue by rrozema** [palmerr23/ESP32-OTA-and-File-Manager#4]
Thanks, i think this is a very useful little project with the FS upload no longer working in arduino ide 2.x. However I can not get it compiled yet, as I don't seem to have the same libraries installed that you do. Can you please add a listed of needed libraries in the readme?

**Comment by palmerr23** [comment]
The code doesn't use any libraries other than those in the standard ESP32 package (Arduino ESP-32 V2.x, based on IDF 4.x).

So, I don't believe your problem is directly related to additional include files (all of which are already listed in the code).

If you want to test for these being available on your installation, try compiling these two ESP32 example programs.

- Webserver/WebUpdate
-  SPIFFS/SPIFFS_Test

There are a couple of other possibilities of what could be causing your issue:

- If you have your project files in OneDrive folder, there's a known issue:  https://github.com/arduino/arduino-builder/issues/254
- I have also had a similar error in the past and found that my file paths were too long. I re-installed the Arduino IDE in portable mode (in the root of my C: drive) and the problems went away.

**Comment by rrozema** [comment]
Software versions I have are
- Arduino IDE 2.0.3
- board package esp32 by Espressif Systems version 2.0.7
- board selected LOLIN(WEMOS) D1 R2 & mini
My project files are not in a OneDrive folder, they are in the standard location in c:\users\<etc>.

Since I do not have issues compiling multiple other projects, before re-installing arduino ide I would like to first research more what exactly is going on. So following your suggestion I wanted to try compiling the examples. I was however not able to locate in my list of examples in the IDE the exact both example names you mention. What I do notice is that there seem to be no references to SPIFFS in my examples lists. LittleFS however is in there in multiple examples. I recall reading some information recently that SPIFFS can act up when the volume fills up, whereas LittleFS does work properly. Could it be that SPIFFS has been replaced by LittleFS as the standard FS to use in ide releases more recent than yours? I did try compiling the following examples, did you mean any of these? If not, can you give me more information where to find the ones you need me to verify?
- ESP8266WebServer\WebUpdate (Verifies successfully)
- LittleFS\Speedtest (Verifies successfully)
- FStools\Basic_example  (Verifies successfully, plus this is the only example I could find using SPIFFS: it does a conversion of a SPIFFS partition into LittleFS)
- FStools\custom_FS_example (Verifies successfully)
- ESP8266httpUpdate\httpUpdateLittleFS (Verifies successfully)

I think I found something!. After changing the board to WEMOS D1 MINI ESP32, I now do see SPIFFS examples. Going to try those!

**Comment by rrozema** [comment]
Using the WEMOS D1 MINI ESP32 board definition I can indeed compile the examples you mention
- WebServer\WebUpdate (verifies successfully)
- SPIFFS\SPIFFS_Test (Verifies successfully)
And also your project verifies fine. I can however not upload either of them, as my board is not an official WEMOS D1 Mini and the upload fails with this output:

> Sketch uses 819609 bytes (62%) of program storage space. Maximum is 1310720 bytes.
> Global variables use 46764 bytes (14%) of dynamic memory, leaving 280916 bytes for local variables. Maximum is 327680 bytes.
> esptool.py v4.5
> Serial port COM4
> 
> A fatal error occurred: Could not open COM4, the port doesn't exist
> Failed uploading: uploading error: exit status 2

So, I think we can conclude your project is fine for official WEMOS D1 mini, but not for many other esp boards. We will need some more tinkering on which libraries to use for those.

edit: 
Using board "LOLIN(WEMOS) D1 mini (clone)" results in the same compile errors I had with my original board definition

> C:\Users\richard.ROZEMA\Documents\Arduino\ESP32-OTA-FILESYS\ESP32_OTA_FILESYS\ESP32_OTA_FILESYS.ino:28:10: fatal error: WiFi.h: No such file or directory
>    28 | #include <WiFi.h>
>       |          ^~~~~~~~
> compilation terminated.
> 
> exit status 1
> 
> Compilation error: WiFi.h: No such file or directory

**Comment by palmerr23** [comment]
Good that you have got this far.

It would seem that you might not need to tinker with the libraries, as you have a successful compile.  You seem to have an upload issue at this stage.

What you may have is a common error with "off market" ESP32's - that they fail to respond properly to a USB request to go into boot mode. The most likely is that you need to press the BOOT switch while the utility is trying to connect (during the '.....'s). There are plenty of good discussions on the web about this issue.

With the WiFi.h not found error , that's just a mystery - as all ESPs have WiFi! Sounds like a poorly constructed board file. I have duplicated the issue on my machine - so it's not just your installation with the problem.

**Comment by palmerr23** [comment]
As there's been no dialogue on this issue for 3 weeks, I'm closing it.
